"""Phase 2 — PDF extraction and duplicate-import refusal.

The extractor is a tool rather than a service module, so it is imported by path.
That is the point of the design: no PDF parser reaches the service image or the
request path, and the tool's only output is the JSON `/packs/load` already takes.

The fixture is a real PDF, generated by `tools/fixtures/make_exam_pdf.py` and
read back through pypdf exactly as a real paper would be. It carries the cases
that actually break extraction: two pages, two numbering styles, a sub-part, a
wrapped question, printed marks, and header/footer furniture.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest
from coursemate_contracts.examprep import ExamPrepPack, ExtractionMethod
from coursemate_service.knowledge.examprep_store import ExamPrepStore

ROOT = Path(__file__).resolve().parents[3]
FIXTURE = ROOT / "tools" / "fixtures" / "oex101_final_2024.pdf"
OFFERING = "course-v1:OpenedX+OEX101+2023"
TENANT = "default"


def _load_tool():
    """Import the extractor by path — it is a tool, not an installed module."""
    spec = importlib.util.spec_from_file_location(
        "extract_pack", ROOT / "tools" / "extract" / "extract_pack.py"
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules["extract_pack"] = module
    spec.loader.exec_module(module)
    return module


#: **A missing `pypdf` FAILS collection; it does not skip (2026-08-15).**
#:
#: This was `pytest.importorskip("pypdf", reason="pypdf is an extraction-only
#: dependency")`. That is true — it is extraction-only — but the consequence was
#: that 19 tests covering the past-paper extractor did not fail without it, they
#: VANISHED, and the run stayed green. A suite that quietly does not run is the
#: failure this repository keeps finding, and `pypdf` is a pure-Python wheel
#: declared in requirements-dev.txt, so there is no environment where skipping is
#: the kind thing to do rather than the misleading one.
#:
#: Same change as `make test-js` on 2026-08-14, for the same reason and against
#: the same objection: the dependency really is optional to the SHIPPED service,
#: and it is not optional to knowing whether the extractor works.
try:
    import pypdf  # noqa: F401
except ImportError as exc:  # pragma: no cover - the message is the point
    raise RuntimeError(
        "pypdf is not installed, so the 19 PDF-extraction tests cannot run. "
        "They used to be skipped silently, which reported a green run for an "
        "untested extractor. Install it with "
        "`pip install -r requirements-dev.txt`."
    ) from exc

tool = _load_tool()


@pytest.fixture(scope="module")
def pack() -> ExamPrepPack:
    assert FIXTURE.exists(), (
        f"{FIXTURE.name} missing — run tools/fixtures/make_exam_pdf.py"
    )
    built, _ = tool.build_pack(
        FIXTURE, offering_id=OFFERING, tenant=TENANT, year=2024, exam_type="final"
    )
    return built


def _by_number(pack: ExamPrepPack) -> dict[str, object]:
    return {q.question_number: q for q in pack.questions}


# --- extraction ------------------------------------------------------------


def test_every_question_on_the_paper_is_found(pack):
    """Five questions across two pages, in two numbering styles."""
    assert sorted(_by_number(pack)) == ["1", "2", "2(b)", "3", "4"]


def test_a_wrapped_question_keeps_its_continuation(pack):
    """Question 2 runs across two printed lines. Losing the tail would produce a
    question that reads as complete and is not — the worst shape, because
    nothing downstream can tell."""
    text = _by_number(pack)["2"].text
    assert text.startswith("Explain how the named release process")
    assert text.endswith("their own installations")


def test_page_numbers_are_tracked_not_assumed(pack):
    """Provenance a rater can check: §11.2b needs the citation to point at
    something real, and "page 1" on a question printed on page 2 is worse than
    no page at all."""
    pages = {n: q.page for n, q in _by_number(pack).items()}
    assert pages == {"1": 1, "2": 1, "2(b)": 1, "3": 2, "4": 2}


def test_marks_are_read_from_the_paper_and_removed_from_the_body(pack):
    """Marks are printed, so they are read rather than derived. Leaving the
    annotation in the text would feed "[10 marks]" to the generator as if it
    were part of the question."""
    assert {n: q.marks for n, q in _by_number(pack).items()} == {
        "1": 2, "2": 10, "2(b)": 5, "3": 15, "4": 3
    }
    assert not any("marks" in q.text.lower() for q in pack.questions)


# --- §7.6 difficulty derivation --------------------------------------------
#
# `difficulty` used to be left None for every extracted question, which left two
# built features idle: the Easy/Medium/Hard selector could not pick a source, and
# per-band mastery recorded everything unbanded.


def test_every_extracted_question_gets_a_derived_difficulty(pack):
    """Both signals — marks and a command verb — are present on this paper, so
    no question should come out unknown."""
    missing = [q.question_number for q in pack.questions if q.difficulty is None]
    assert not missing, f"no difficulty derived for {missing}"


def test_the_derived_difficulty_stays_labelled_as_derived(pack):
    """§7.6: the paper did not print this number, we inferred it. Claiming
    otherwise would present an inference as something the examiner stated."""
    assert all(q.difficulty_is_derived is True for q in pack.questions)


def test_difficulty_separates_recall_from_judgement(pack):
    """The spread is the point. A 2-mark "State" and a 15-mark "Critically
    evaluate" must not land in the same band, or the selector has nothing to
    select on."""
    from coursemate_contracts.examprep import band_of

    by_num = _by_number(pack)
    assert band_of(by_num["1"].difficulty) == "easy"       # 2 marks, "State"
    assert band_of(by_num["3"].difficulty) == "hard"       # 15 marks, "Critically evaluate"
    assert by_num["1"].difficulty < by_num["3"].difficulty


def test_every_difficulty_is_inside_the_contract_range(pack):
    """`QuestionRecord.difficulty` is `ge=0.0, le=1.0`; a derivation that
    overshoots would be refused by the contract at load time, not here."""
    assert all(0.0 <= q.difficulty <= 1.0 for q in pack.questions)


def test_headers_footers_and_rubric_lines_are_not_questions(pack):
    """"Page 1 of 2", "END OF PAPER" and "Answer ALL questions" are furniture.
    Without the filter, a footer is appended to the last question on every
    page."""
    joined = " ".join(q.text for q in pack.questions).lower()
    for noise in ("page 1 of 2", "end of paper", "answer all questions",
                  "time allowed", "university of example"):
        assert noise not in joined, f"furniture leaked into a question: {noise!r}"


def test_sub_parts_are_kept_distinct(pack):
    """2 and 2(b) are different questions with different marks. Merging them
    would produce one question worth 15 that the paper never asked."""
    q2, q2b = _by_number(pack)["2"], _by_number(pack)["2(b)"]
    assert q2.question_id != q2b.question_id
    assert (q2.marks, q2b.marks) == (10, 5)


def test_question_ids_are_stable_across_runs(pack):
    """Derived from the filename and the printed number, so re-extracting the
    same paper yields the same ids — which is what makes a reload a replace
    rather than a duplicate."""
    again, _ = tool.build_pack(
        FIXTURE, offering_id=OFFERING, tenant=TENANT, year=2024, exam_type="final"
    )
    assert [q.question_id for q in again.questions] == [q.question_id for q in pack.questions]
    assert all(q.question_id.startswith("oex101_final_2024.pdf#") for q in pack.questions)


def test_extraction_method_is_recorded(pack):
    """§7.6 lists digital/ocr/vlm. Recording which was used is what lets a later
    OCR pass be distinguished from this one."""
    assert all(q.extraction_method is ExtractionMethod.DIGITAL for q in pack.questions)


def test_the_clo_is_left_unset_for_the_offline_tagger(pack):
    """Still not guessed here. `clo_id` is the tagger's job, and a wrong tag
    files a question under an outcome it does not belong to.

    `difficulty` used to be asserted None alongside it. That is no longer true:
    §7.6's derivation from marks + command verb is now applied at extraction, and
    `difficulty_is_derived` carries the label that keeps the claim honest. See
    the derivation tests above.
    """
    assert all(q.clo_id is None for q in pack.questions)


def test_a_clean_extraction_scores_full_confidence(pack):
    """Confidence describes the EXTRACTION, not the question.

    It reported 0.8 on every question at first: stripping "[10 marks]" also
    stripped the full stop, and the heuristic then penalised the question for
    not ending in one. A confidence that is wrong on the happy path trains the
    operator to ignore the column."""
    assert all(q.confidence == 1.0 for q in pack.questions), {
        n: q.confidence for n, q in _by_number(pack).items()
    }
    assert not any(q.low_confidence_flag for q in pack.questions)


def test_a_truncated_question_is_flagged_low_confidence():
    """The failure that matters: a question cut short still looks like a
    question. It must arrive flagged rather than silently short."""
    record = tool.to_record(
        {"question_number": "9", "page": 1, "lines": ["Explain why"]},
        offering_id=OFFERING, tenant=TENANT, source_doc_id="p.pdf",
        year=2024, exam_type="final",
    )
    assert record.confidence < 0.8
    assert record.low_confidence_flag is True


def test_a_page_with_no_text_layer_is_reported_not_silently_skipped():
    """A scanned paper yields nothing. Reporting zero honestly is the whole
    point — OCR is deferred, and a silent empty pack is indistinguishable from
    a paper with no questions."""
    _, report = tool.build_pack(
        FIXTURE, offering_id=OFFERING, tenant=TENANT, year=None, exam_type=None
    )
    assert report["pages"] == 2
    assert report["empty_pages"] == 0
    assert report["questions"] == 5


# --- duplicate imports -----------------------------------------------------


def test_the_hash_is_of_the_document_not_the_pack(pack):
    """Hashing the pack would change whenever the parser improved, so a better
    extraction of the same paper would look like a new document and double the
    bank."""
    assert pack.content_sha256 == tool.content_sha256(FIXTURE.read_bytes())
    assert len(pack.content_sha256) == 64


def test_reimporting_the_same_document_is_refused(tmp_path, monkeypatch):
    """A pack load REPLACES the offering's questions, so a duplicate is not
    merely wasteful: re-importing paper A after paper B silently discards B and
    still reports a successful load."""
    from fastapi import HTTPException

    import coursemate_service.api.packs as packs

    store = ExamPrepStore(tmp_path / "e.db")
    monkeypatch.setattr(packs, "get_examprep_store", lambda: store)

    built, _ = tool.build_pack(
        FIXTURE, offering_id=OFFERING, tenant=TENANT, year=2024, exam_type="final"
    )

    first = packs.load_pack(built)
    assert first["questions"] == 5
    assert first["duplicate_checked"] is True
    assert first["reloaded"] is False

    with pytest.raises(HTTPException) as exc:
        packs.load_pack(built)
    assert exc.value.status_code == 409
    assert "already imported" in exc.value.detail


def test_force_allows_a_corrected_reextraction(tmp_path, monkeypatch):
    """A better extraction of the same PDF is legitimate. The refusal is a
    guard, not a wall."""
    import coursemate_service.api.packs as packs

    store = ExamPrepStore(tmp_path / "e.db")
    monkeypatch.setattr(packs, "get_examprep_store", lambda: store)
    built, _ = tool.build_pack(
        FIXTURE, offering_id=OFFERING, tenant=TENANT, year=2024, exam_type="final"
    )

    packs.load_pack(built)
    again = packs.load_pack(built, force=True)
    assert again["reloaded"] is True
    assert again["questions"] == 5
    # Replaced, not appended.
    assert len(store.search_questions(tenant=TENANT, offering_id=OFFERING, limit=50)) == 5


def test_a_pack_with_no_hash_says_it_was_not_checked(tmp_path, monkeypatch):
    """"Unknown" is not "new". A hand-written pack cannot be duplicate-checked,
    and the loader reports that rather than implying a check happened."""
    import coursemate_service.api.packs as packs

    store = ExamPrepStore(tmp_path / "e.db")
    monkeypatch.setattr(packs, "get_examprep_store", lambda: store)

    plain = ExamPrepPack(offering_id=OFFERING, tenant=TENANT)
    out = packs.load_pack(plain)
    assert out["duplicate_checked"] is False
    # And loading it twice is allowed, because nothing can say it is the same.
    assert packs.load_pack(plain)["duplicate_checked"] is False


def test_a_different_document_is_not_a_duplicate(tmp_path):
    """The guard keys on content, so a second paper loads normally."""
    store = ExamPrepStore(tmp_path / "e.db")
    built, _ = tool.build_pack(
        FIXTURE, offering_id=OFFERING, tenant=TENANT, year=2024, exam_type="final"
    )
    store.load_pack(built)

    other = built.model_copy(update={"content_sha256": "b" * 64})
    assert store.already_imported(
        tenant=TENANT, offering_id=OFFERING, content_sha256=other.content_sha256
    ) is None


def test_the_same_document_in_another_offering_is_not_a_duplicate(tmp_path):
    """Import history is per offering, like everything else: the same paper is
    legitimately used by CS-101 Fall 2026 and its rerun a year later."""
    store = ExamPrepStore(tmp_path / "e.db")
    built, _ = tool.build_pack(
        FIXTURE, offering_id=OFFERING, tenant=TENANT, year=2024, exam_type="final"
    )
    store.load_pack(built)
    assert store.already_imported(
        tenant=TENANT, offering_id="course-v1:Other+X+Y",
        content_sha256=built.content_sha256,
    ) is None


# --- the tool's own output contract ----------------------------------------


def test_the_tool_emits_json_the_loader_accepts(pack):
    """The tool's whole interface: JSON that /packs/load validates unchanged. If
    these drift, the operator finds out through a 422 at load time."""
    payload = json.loads(json.dumps(pack.model_dump(mode="json")))
    assert ExamPrepPack(**payload).content_sha256 == pack.content_sha256


# --- F1: the examiner's answer, where the paper prints one ------------------


def test_this_paper_prints_no_answers(pack):
    """The honest state of the live bank. OEX101 is a question paper — "Answer
    ALL questions", two hours — with no model answers and no marking scheme, so
    every reference answer here is None and the UI offers nothing to reveal."""
    assert all(q.reference_answer is None for q in pack.questions)
    assert all(q.has_reference_answer is False for q in pack.questions)


def test_the_rubric_line_is_not_mistaken_for_an_answer():
    """"Answer ALL questions" is printed on the front of most papers. Reading it
    as a model answer would truncate the first question and present its tail to
    students as the examiner's words."""
    q, a = tool.split_reference_answer(["Answer ALL questions. Time allowed: 2 hours."])
    assert a == []
    assert q == ["Answer ALL questions. Time allowed: 2 hours."]


def test_the_word_answer_inside_a_question_is_not_a_marker():
    q, a = tool.split_reference_answer(["State the rule and answer briefly."])
    assert a == []


@pytest.mark.parametrize("marker", [
    "Answer:", "Model answer:", "Marking scheme:", "Mark scheme:", "Solution:",
])
def test_a_printed_answer_is_split_out(marker):
    lines = ["Name two major members.", f"{marker} edX and Axim.", "One mark each."]
    q, a = tool.split_reference_answer(lines)
    assert q == ["Name two major members."]
    assert a == ["edX and Axim.", "One mark each."]


def test_the_answer_is_removed_from_the_question_text():
    """The split matters most for what it takes OUT: leaving the answer in the
    question text would feed it to the generator as part of the prompt."""
    lines = ["Name two major members. [3 marks]", "Answer: edX and Axim."]
    q, a = tool.split_reference_answer(lines)
    assert "edX and Axim" not in " ".join(q)


def test_an_extracted_answer_carries_its_own_provenance():
    rec = tool.to_record(
        {"lines": ["Name two members.", "Answer: edX and Axim."],
         "page": 4, "question_number": "7"},
        offering_id=OFFERING, tenant=TENANT, source_doc_id="paper.pdf",
        year=2024, exam_type="final",
    )
    assert rec.reference_answer == "edX and Axim."
    assert rec.reference_answer_source_doc_id == "paper.pdf"
    assert rec.reference_answer_page == 4
    assert "edX and Axim" not in rec.text


def test_no_answer_means_no_answer_provenance():
    """A citation pointing at a document that does not contain the text would be
    worse than no citation."""
    rec = tool.to_record(
        {"lines": ["Name two members. [3 marks]"], "page": 4, "question_number": "7"},
        offering_id=OFFERING, tenant=TENANT, source_doc_id="paper.pdf",
        year=2024, exam_type="final",
    )
    assert rec.reference_answer is None
    assert rec.reference_answer_source_doc_id is None
    assert rec.reference_answer_page is None
